import type { Metadata } from "next";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import AntdConfigProvider from '@/components/ConfigProvider';
import AppHeader from '@/components/AppHeader'
import localFont from 'next/font/local'
import "./globals.css";
import Indexes from "@/components/Indexes/Indexes";

const bodyFont = localFont({
  src: [
    {
      path: '../public/fonts/Shabnam-Light.woff',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/Shabnam-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/Shabnam.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Shabnam.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Shabnam-Bold.woff',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/Shabnam-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--body-font'
});
const monospace = localFont({
  src: [
    {
      path: '../public/fonts/Vazir-Code-Hack-Extra-Height-WOL.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Vazir-Code-Hack-Extra-Height-WOL.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-mono'
})



export const metadata: Metadata = {
  title: "داشبورد غدیر",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl" className={bodyFont.className + ' ' + monospace.variable + ' ' + bodyFont.variable}>
      <body>
        <AntdRegistry>
          <AntdConfigProvider>
            <AppHeader />
            <Indexes />
            <div className="container py-3 mx-auto">
              {children}
            </div>
          </AntdConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
