import type { Metadata } from "next";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ConfigProvider } from 'antd';
import AppHeader from '@/components/AppHeader'
import faIR from 'antd/locale/fa_IR'
import type { ThemeConfig } from 'antd';
import localFont from 'next/font/local'
import "./globals.css";

const bodyFont = localFont({
  src: [
    {
      path: '../public/fonts/Shabnam-Light.woff',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/Shabnam-Light.woff2',
      weight: '300',
      style: 'normal',
    },
    {
      path: '../public/fonts/Shabnam.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Shabnam.woff2',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Shabnam-Bold.woff',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/Shabnam-Bold.woff2',
      weight: '700',
      style: 'normal',
    },
  ],
  variable: '--body-font'
});
const monospace = localFont({
  src: [
    {
      path: '../public/fonts/Vazir-Code-Hack-Extra-Height-WOL.woff',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/Vazir-Code-Hack-Extra-Height-WOL.woff2',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-mono'
})

const config: ThemeConfig = {
  token: {
    fontFamily: 'bodyFont',
  },
  components: {
    Layout: {
      bodyBg: '#f0f2f5',
      headerBg: '#f9f9f9',
    },
    Menu: {
      colorBgContainer: '#f9f9f9',
    },
    Table: {
      cellPaddingBlock: 8
    }
  }
};

export const metadata: Metadata = {
  title: "داشبورد غدیر",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa-IR" dir="rtl" className={bodyFont.className + ' ' + monospace.variable + ' ' + bodyFont.variable}>
      <body>
        <AntdRegistry>
          <ConfigProvider
            locale={faIR}
            direction="rtl"
            theme={config}
          >
            <AppHeader />
            <div className="container py-3 mx-auto">
              {children}
            </div>
          </ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
